version: '3'

services:
  admin:
    build:
      context: .
      dockerfile: src/admin/Dockerfile
    image: io/admin
    restart: always
    ports:
      - "5090:80"
    expose:
      - "5090"
    depends_on:
      - mongo
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    image: io/api
    restart: always
    ports:
      - "5001:80"
  chat:
    build:
      context: .
      dockerfile: src/chat/Dockerfile
    image: io/chat
    restart: always
    ports:
      - "5050:80"
    volumes:
      - ./assets:/app/dist/assets
    depends_on:
      - hub
      - api
      - mongo
  chron:
    build:
      context: .
      dockerfile: src/chron/Dockerfile
    image: io/chron
    restart: always
    ports:
      - "5080:80"
    depends_on:
      - api
      - hub
  hub:
    build:
      context: .
      dockerfile: src/hub/Dockerfile
    image: io/hub
    restart: always
    ports:
      - "5060:80"
    expose:
      - "5060"
  logger:
    build:
      context: .
      dockerfile: src/logger/Dockerfile
    image: io/logger
    restart: always
    depends_on:
      - hub
      - mongo
  overlay:
    build:
      context: .
      dockerfile: src/overlay/Dockerfile
    image: io/overlay
    restart: always
    ports:
      - "5000:80"
    expose:
      - "5000"
    volumes:
      - ./assets:/app/dist/wwwroot/assets
    depends_on:
      - hub
  streamnotes:
    build:
      context: .
      dockerfile: src/stream-notes/Dockerfile
    image: io/streamnotes
    restart: always
    depends_on:
      - api
      - hub
  user:
    build:
      context: .
      dockerfile: src/user/Dockerfile
    image: io/user
    restart: always
    ports:
      - "5070:80"
    depends_on:
      - api
      - mongo
  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - "mongodata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongoex:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
volumes:
  mongodata:
