version: '3'

services:
  shared:
    build: ./src/shared
    image: io-shared
    env_file:
      - .env
  admin:
    build: ./src/admin
    image: io-admin
    restart: always
    ports:
      - "5090:80"
    env_file:
      - .env
    depends_on:
      - mongo
      - shared
  api:
    build: ./src/api
    image: io-api
    restart: always
    ports:
      - "5001:80"
    env_file:
      - .env
    depends_on:
      - shared
  chat:
    build: ./src/chat
    image: io-chat
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./assets:/app/chat/dist/assets
    depends_on:
      - hub
      - api
      - mongo
      - shared
  chron:
    build: ./src/chron
    image: io-chron
    restart: always
    ports:
      - "5080:80"
    env_file:
      - .env
    depends_on:
      - api
      - hub
      - shared
  hub:
    build: ./src/hub
    image: io-hub
    restart: always
    ports:
      - "5060:80"
    env_file:
      - .env
    depends_on:
      - shared
  logger:
    build: ./src/logger
    image: io-logger
    restart: always
    env_file:
      - .env
    depends_on:
      - hub
      - mongo
      - shared
  overlay:
    build: ./src/overlay
    image: io-overlay
    restart: always
    ports:
      - "5000:80"
    env_file:
      - .env
    volumes:
      - ./assets:/app/overlay/dist/wwwroot/assets
    depends_on:
      - hub
      - shared
  streamnotes:
    build: ./src/stream-notes
    image: io-streamnotes
    restart: always
    env_file:
      - .env
    depends_on:
      - api
      - hub
      - shared
  user:
    build: ./src/user
    image: io-user
    restart: always
    ports:
      - "5070:80"
    env_file:
      - .env
    depends_on:
      - api
      - mongo
      - shared
  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - "mongodata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongoex:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
volumes:
  mongodata:
